##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/thivao/test.v2.th.ivao.aero/
    - /bin/cp -R public $DEPLOYPATH
    #- /bin/cp -R assets $DEPLOYPATH
    #- /bin/cp -R css $DEPLOYPATH
    #- /bin/cp -R fonts $DEPLOYPATH
    #- /bin/cp -R img $DEPLOYPATH
    #- /bin/cp -R js $DEPLOYPATH
    #- /bin/cp index.html $DEPLOYPATH